<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>eShift_Logistics_System</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Resources\Icons\" />
    <Folder Include="Resources\Images\" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\dotnet-build.yml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.12.1" />
    <PackageReference Include="MySql.Data" Version="9.3.0" />
  </ItemGroup>

</Project>